/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 07 10:53:30 KST 2017
 */

package org.prevayler.foundation.network;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.fail;

import java.io.IOException;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class Network_ESTest4 extends Network_ESTest_scaffolding4 {

  @Test
  public void test1()  throws Throwable  {
      StubbornNetworkImpl stubbornNetworkImpl0 = new StubbornNetworkImpl();
      StubbornClientReceiverImpl stubbornClientReceiverImpl0 = (StubbornClientReceiverImpl)stubbornNetworkImpl0.findServer("1lhJzI[hgLU", (-2477), (ObjectReceiver) null);
      assertFalse(stubbornClientReceiverImpl0.isInterrupted());
  }

  @Test
  public void test2()  throws Throwable  {
      StubbornNetworkImpl stubbornNetworkImpl0 = new StubbornNetworkImpl();
      try { 
        stubbornNetworkImpl0.stopService((-1));
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Port Not in Service
         //
         assertThrownBy("org.prevayler.foundation.network.BaseNetworkImpl", e);
      }
  }

  @Test
  public void test3()  throws Throwable  {
      NetworkImpl networkImpl0 = new NetworkImpl();
      // Undeclared exception!
      try { 
        networkImpl0.startService((Service) null, (-2831));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Port value out of range: -2831
         //
         assertThrownBy("org.evosuite.runtime.mock.java.net.MockServerSocket", e);
      }
  }

  @Test
  public void test4()  throws Throwable  {
      NetworkImpl networkImpl0 = new NetworkImpl();
      StubbornClientReceiverImpl stubbornClientReceiverImpl0 = new StubbornClientReceiverImpl((ObjectSocket) null, (Service) null);
      // Undeclared exception!
      try { 
        networkImpl0.findServer("rHX#", (-255), stubbornClientReceiverImpl0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // port out of range:-255
         //
         assertThrownBy("java.net.InetSocketAddress", e);
      }
  }

  
}
